//
//  codeConverter.swift
//  countriesJsonPractice
//
//  Created by Chris Hovey on 6/16/16.
//  Copyright © 2016 Chris Hovey. All rights reserved.
//

import Foundation

class codeConverter{
    
    var countriesFullConverterArray = [
        "AFG":	"Afghanistan",
        "ALB":	"Albania",
        "DZA":	"Algeria",
        "ASM":	"American Samoa",
        "AND":	"Andorra",
        "AGO":	"Angola",
        "AIA":	"Anguilla",
        "ATA":	"Antarctica",
        "ATG":	"Antigua and Barbuda",
        "ARG":	"Argentina",
        "ARM":	"Armenia",
        "ABW":	"Aruba",
        "AUS":	"Australia",
        "AUT":	"Austria",
        "AZE":	"Azerbaijan",
        "BHS":	"Bahamas",
        "BHR":	"Bahrain",
        "BGD":	"Bangladesh",
        "BRB":	"Barbados",
        "BLR":	"Belarus",
        "BEL":	"Belgium",
        "BLZ":	"Belize",
        "BEN":	"Benin",
        "BMU":	"Bermuda",
        "BTN":	"Bhutan",
        "BOL":	"Bolivia",
        "BES":	"Bonaire",
        "BIH":	"Bosnia and Herzegovina",
        "BWA":	"Botswana",
        "BVT":	"Bouvet Island",
        "BRA":	"Brazil",
        "IOT":	"British Indian Ocean Territory",
        "BRN":	"Brunei Darussalam",
        "BGR":	"Bulgaria",
        "BFA":	"Burkina Faso",
        "BDI":	"Burundi",
        "KHM":	"Cambodia",
        "CMR":	"Cameroon",
        "CAN":	"Canada",
        "CPV":	"Cape Verde",
        "CYM":	"Cayman Islands",
        "CAF":	"Central African Republic",
        "TCD":	"Chad",
        "CHL":	"Chile",
        "CHN":	"China",
        "CXR":	"Christmas Island",
        "CCK":	"Cocos (Keeling) Islands",
        "COL":	"Colombia",
        "COM":	"Comoros",
        "COG":	"Congo",
        "COD":	"Democratic Republic of the Congo",
        "COK":	"Cook Islands",
        "CRI":	"Costa Rica",
        "HRV":	"Croatia",
        "CUB":	"Cuba",
        "CUW":	"CuraÃ§ao",
        "CYP":	"Cyprus",
        "CZE":	"Czech Republic",
        "CIV":	"CÃ´te d'Ivoire",
        "DNK":	"Denmark",
        "DJI":	"Djibouti",
        "DMA":	"Dominica",
        "DOM":	"Dominican Republic",
        "ECU":	"Ecuador",
        "EGY":	"Egypt",
        "SLV":	"El Salvador",
        "GNQ":	"Equatorial Guinea",
        "ERI":	"Eritrea",
        "EST":	"Estonia",
        "ETH":	"Ethiopia",
        "FLK":	"Falkland Islands (Malvinas)",
        "FRO":	"Faroe Islands",
        "FJI":	"Fiji",
        "FIN":	"Finland",
        "FRA":	"France",
        "GUF":	"French Guiana",
        "PYF":	"French Polynesia",
        "ATF":	"French Southern Territories",
        "GAB":	"Gabon",
        "GMB":	"Gambia",
        "GEO":	"Georgia",
        "DEU":	"Germany",
        "GHA":	"Ghana",
        "GIB":	"Gibraltar",
        "GRC":	"Greece",
        "GRL":	"Greenland",
        "GRD":	"Grenada",
        "GLP":	"Guadeloupe",
        "GUM":	"Guam",
        "GTM":	"Guatemala",
        "GGY":	"Guernsey",
        "GIN":	"Guinea",
        "GNB":	"Guinea-Bissau",
        "GUY":	"Guyana",
        "HTI":	"Haiti",
        "HMD":	"Heard Island and McDonald Mcdonald Islands",
        "VAT":	"Holy See (Vatican City State)",
        "HND":	"Honduras",
        "HKG":	"Hong Kong",
        "HUN":	"Hungary",
        "ISL":	"Iceland",
        "IND":	"India",
        "IDN":	"Indonesia",
        "IRN":	"Iran, Islamic Republic of",
        "IRQ":	"Iraq",
        "IRL":	"Ireland",
        "IMN":	"Isle of Man",
        "ISR":	"Israel",
        "ITA":	"Italy",
        "JAM":	"Jamaica",
        "JPN":	"Japan",
        "JEY":	"Jersey",
        "JOR":	"Jordan",
        "KAZ":	"Kazakhstan",
        "KEN":	"Kenya",
        "KIR":	"Kiribati",
        "PRK":	"Korea, Democratic People's Republic of",
        "KOR":	"Korea, Republic of",
        "KWT":	"Kuwait",
        "KGZ":	"Kyrgyzstan",
        "LAO":	"Lao People's Democratic Republic",
        "LVA":	"Latvia",
        "LBN":	"Lebanon",
        "LSO":	"Lesotho",
        "LBR":	"Liberia",
        "LBY":	"Libya",
        "LIE":	"Liechtenstein",
        "LTU":	"Lithuania",
        "LUX":	"Luxembourg",
        "MAC":	"Macao",
        "MKD":	"Macedonia, the Former Yugoslav Republic of",
        "MDG":	"Madagascar",
        "MWI":	"Malawi",
        "MYS":	"Malaysia",
        "MDV":	"Maldives",
        "MLI":	"Mali",
        "MLT":	"Malta",
        "MHL":	"Marshall Islands",
        "MTQ":	"Martinique",
        "MRT":	"Mauritania",
        "MUS":	"Mauritius",
        "MYT":	"Mayotte",
        "MEX":	"Mexico",
        "FSM":	"Micronesia, Federated States of",
        "MDA":	"Moldova, Republic of",
        "MCO":	"Monaco",
        "MNG":	"Mongolia",
        "MNE":	"Montenegro",
        "MSR":	"Montserrat",
        "MAR":	"Morocco",
        "MOZ":	"Mozambique",
        "MMR":	"Myanmar",
        "NAM":	"Namibia",
        "NRU":	"Nauru",
        "NPL":	"Nepal",
        "NLD":	"Netherlands",
        "NCL":	"New Caledonia",
        "NZL":	"New Zealand",
        "NIC":	"Nicaragua",
        "NER":	"Niger",
        "NGA":	"Nigeria",
        "NIU":	"Niue",
        "NFK":	"Norfolk Island",
        "MNP":	"Northern Mariana Islands",
        "NOR":	"Norway",
        "OMN":	"Oman",
        "PAK":	"Pakistan",
        "PLW":	"Palau",
        "PSE":	"Palestine, State of",
        "PAN":	"Panama",
        "PNG":	"Papua New Guinea",
        "PRY":	"Paraguay",
        "PER":	"Peru",
        "PHL":	"Philippines",
        "PCN":	"Pitcairn",
        "POL":	"Poland",
        "PRT":	"Portugal",
        "PRI":	"Puerto Rico",
        "QAT":	"Qatar",
        "ROU":	"Romania",
        "RUS":	"Russian Federation",
        "RWA":	"Rwanda",
        "REU":	"Reunion",
        "BLM":	"Saint Barthelemy",
        "SHN":	"Saint Helena",
        "KNA":	"Saint Kitts and Nevis",
        "LCA":	"Saint Lucia",
        "MAF":	"Saint Martin (French part)",
        "SPM":	"Saint Pierre and Miquelon",
        "VCT":	"Saint Vincent and the Grenadines",
        "WSM":	"Samoa",
        "SMR":	"San Marino",
        "STP":	"Sao Tome and Principe",
        "SAU":	"Saudi Arabia",
        "SEN":	"Senegal",
        "SRB":	"Serbia",
        "SYC":	"Seychelles",
        "SLE":	"Sierra Leone",
        "SGP":	"Singapore",
        "SXM":	"Sint Maarten (Dutch part)",
        "SVK":	"Slovakia",
        "SVN":	"Slovenia",
        "SLB":	"Solomon Islands",
        "SOM":	"Somalia",
        "ZAF":	"South Africa",
        "SGS":	"South Georgia and the South Sandwich Islands",
        "SSD":	"South Sudan",
        "ESP":	"Spain",
        "LKA":	"Sri Lanka",
        "SDN":	"Sudan",
        "SUR":	"Suriname",
        "SJM":	"Svalbard and Jan Mayen",
        "SWZ":	"Swaziland",
        "SWE":	"Sweden",
        "CHE":	"Switzerland",
        "SYR":	"Syrian Arab Republic",
        "TWN":	"Taiwan, Province of China",
        "TJK":	"Tajikistan",
        "TZA":	"United Republic of Tanzania",
        "THA":	"Thailand",
        "TLS":	"Timor-Leste",
        "TGO":	"Togo",
        "TKL":	"Tokelau",
        "TON":	"Tonga",
        "TTO":	"Trinidad and Tobago",
        "TUN":	"Tunisia",
        "TUR":	"Turkey",
        "TKM":	"Turkmenistan",
        "TCA":	"Turks and Caicos Islands",
        "TUV":	"Tuvalu",
        "UGA":	"Uganda",
        "UKR":	"Ukraine",
        "ARE":	"United Arab Emirates",
        "GBR":	"United Kingdom",
        "USA":	"United States",
        "UMI":	"United States Minor Outlying Islands",
        "URY":	"Uruguay",
        "UZB":	"Uzbekistan",
        "VUT":	"Vanuatu",
        "VEN":	"Venezuela",
        "VNM":	"Viet Nam",
        "VGB":	"British Virgin Islands",
        "VIR":	"US Virgin Islands",
        "WLF":	"Wallis and Futuna",
        "ESH":	"Western Sahara",
        "YEM":	"Yemen",
        "ZMB":	"Zambia",
        "ZWE":	"Zimbabwe",
        "ALA":	"Aland Islands",
    ]
    
    var languagesConverterArray = [
        "AB":	"Abkhazian",
        "AA":	"Afar",
        "AF":	"Afrikaans",
        "SQ":	"Albanian",
        "AM":	"Amharic",
        "AR":	"Arabic",
        "HY":	"Armenian",
        "AS":	"Assamese",
        "AY":	"Aymara",
        "AZ":	"Azerbaijani",
        "BA":	"Bashkir",
        "EU":	"Basque",
        "BN":	"Bengali, Bangla",
        "DZ":	"Bhutani",
        "BH":	"Bihari",
        "BI":	"Bislama",
        "BR":	"Breton",
        "BG":	"Bulgarian",
        "MY":	"Burmese",
        "BE":	"Byelorussian",
        "KM":	"Cambodian",
        "CA":	"Catalan",
        "ZH":	"Chinese",
        "CO":	"Corsican",
        "HR":	"Croatian",
        "CS":	"Czech",
        "DA":	"Danish",
        "NL":	"Dutch",
        "EN":	"English, American",
        "EO":	"Esperanto",
        "ET":	"Estonian",
        "FO":	"Faeroese",
        "FJ":	"Fiji",
        "FI":	"Finnish",
        "FR":	"French",
        "FY":	"Frisian",
        "GD":	"Gaelic (Scots Gaelic)",
        "GL":	"Galician",
        "KA":	"Georgian",
        "DE":	"German",
        "EL":	"Greek",
        "KL":	"Greenlandic",
        "GN":	"Guarani",
        "GU":	"Gujarati",
        "HA":	"Hausa",
        "IW":	"Hebrew",
        "HI":	"Hindi",
        "HU":	"Hungarian",
        "IS":	"Icelandic",
        "IN":	"Indonesian",
        "IA":	"Interlingua",
        "IE":	"Interlingue",
        "IK":	"Inupiak",
        "GA":	"Irish",
        "IT":	"Italian",
        "JA":	"Japanese",
        "JW":	"Javanese",
        "KN":	"Kannada",
        "KS":	"Kashmiri",
        "KK":	"Kazakh",
        "RW":	"Kinyarwanda",
        "KY":	"Kirghiz",
        "RN":	"Kirundi",
        "KO":	"Korean",
        "KU":	"Kurdish",
        "LO":	"Laothian",
        "LA":	"Latin",
        "LV":	"Latvian, Lettish",
        "LN":	"Lingala",
        "LT":	"Lithuanian",
        "MK":	"Macedonian",
        "MG":	"Malagasy",
        "MS":	"Malay",
        "ML":	"Malayalam",
        "MT":	"Maltese",
        "MI":	"Maori",
        "MR":	"Marathi",
        "MO":	"Moldavian",
        "MN":	"Mongolian",
        "NA":	"Nauru",
        "NE":	"Nepali",
        "NO":	"Norwegian",
        "OC":	"Occitan",
        "OR":	"Oriya",
        "OM":	"Oromo, Afan",
        "PS":	"Pashto, Pushto",
        "FA":	"Persian",
        "PL":	"Polish",
        "PT":	"Portuguese",
        "PA":	"Punjabi",
        "QU":	"Quechua",
        "RM":	"Rhaeto-Romance",
        "RO":	"Romanian",
        "RU":	"Russian",
        "SM":	"Samoan",
        "SG":	"Sangro",
        "SA":	"Sanskrit",
        "SR":	"Serbian",
        "SH":	"Serbo-Croatian",
        "ST":	"Sesotho",
        "TN":	"Setswana",
        "SN":	"Shona",
        "SD":	"Sindhi",
        "SI":	"Singhalese",
        "SS":	"Siswati",
        "SK":	"Slovak",
        "SL":	"Slovenian",
        "SO":	"Somali",
        "ES":	"Spanish",
        "SU":	"Sudanese",
        "SW":	"Swahili",
        "SV":	"Swedish",
        "TL":	"Tagalog",
        "TG":	"Tajik",
        "TA":	"Tamil",
        "TT":	"Tatar",
        "TE":	"Tegulu",
        "TH":	"Thai",
        "BO":	"Tibetan",
        "TI":	"Tigrinya",
        "TO":	"Tonga",
        "TS":	"Tsonga",
        "TR":	"Turkish",
        "TK":	"Turkmen",
        "TW":	"Twi",
        "UK":	"Ukrainian",
        "UR":	"Urdu",
        "UZ":	"Uzbek",
        "VI":	"Vietnamese",
        "VO":	"Volapuk",
        "CY":	"Welsh",
        "WO":	"Wolof",
        "XH":	"Xhosa",
        "JI":	"Yiddish",
        "YO":	"Yoruba",
        "ZU":	"Zulu",
    ]
    
    func convertToFullName(countryCodes: [String]) -> String{
        var countriesFullName = [String]()
        if countryCodes.count == 0 {
            print("1")
            return "No bordering countries"
        }
        print("2")
        for countryCode in countryCodes{
            print(countryCode)
            if let countryAAA = countriesFullConverterArray[countryCode]{
                print("4")
                countriesFullName.append(countryAAA.stringByReplacingOccurrencesOfString(",", withString: "-"))
            }
        }
        let stringFinal = parseArray(countriesFullName)
        return stringFinal
    }
    
    func convertToFullLanguage(languageCodes: [String]) -> String{
        var languagesFullName = [String]()
        if languageCodes.count == 0 {
            return ""
        }
        for languageCode in languageCodes{
            if let languageAAA: String = languagesConverterArray[languageCode.uppercaseString]{
                languagesFullName.append(languageAAA)
            }
        }
        let stringFinal = parseArray(languagesFullName)
        return stringFinal
    }
    
    func parseArray(holds: [String]) -> String{
        if holds.count > 0{
            var addString: String = ""
            var x = 0
            for hold in holds{
                addString = addString + "\(hold)"
                x = x + 1
                if x < holds.count{
                    addString = addString + ", "
                }
            }
            return addString
        }
        return "no data"
    }

    
    
    
}